Repository aengzu/AILectureProject, pull requests merged in 2024-11, with the labels that each got.

#5 [Design] homeView, CalendarView 제작
  frontend/AILectureProjectClient/build.gradle.kts
  frontend/AILectureProjectClient/composeApp/build.gradle.kts
  frontend/AILectureProjectClient/composeApp/src/androidMain/kotlin/org/ral/project/MainActivity.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/domain/usecase/GetResultUseCase.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/domain/usecase/UploadPhotoUseCase.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/theme/Theme.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/.gitkeep
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/Calendar/CalendarView.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/Calendar/component/CalendarContent.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/core/BottomNavigationBar.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/core/Navigation.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/home/HomeView.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/home/component/CardSection.kt
  frontend/AILectureProjectClient/composeApp/src/commonMain/kotlin/org/ral/project/presentation/view/home/component/TitleSection.kt
  frontend/AILectureProjectClient/gradle/libs.versions.toml
Labels: 🎨 Design

#6 Chore: 연습
  backend/ex1/main.py
Labels: ⚙️ Setting

#13 [Design] 디자인 수정
  frontend/petkinFE/.idea/deploymentTargetDropDown.xml
  frontend/petkinFE/.idea/misc.xml
  frontend/petkinFE/.idea/vcs.xml
  frontend/petkinFE/app/build.gradle.kts
  frontend/petkinFE/app/src/main/AndroidManifest.xml
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainActivity.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/BottomNavigationBar.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/components/TitleSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/login/LoginView.kt
  frontend/petkinFE/app/src/main/res/animator/logo_animator.xml
  frontend/petkinFE/app/src/main/res/drawable/animated_logo.xml
  frontend/petkinFE/app/src/main/res/drawable/btn_kakao.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_bone.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_calendar.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_camera.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_capsule.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_drop.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_edit_box.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_goal.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_heart.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_home.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_menu.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_pen.xml
  frontend/petkinFE/app/src/main/res/drawable/ic_user.xml
  frontend/petkinFE/app/src/main/res/drawable/logo_petkin.xml
  frontend/petkinFE/app/src/main/res/values-v31/splash.xml
  frontend/petkinFE/app/src/main/res/values/colors.xml
  frontend/petkinFE/app/src/main/res/values/splash.xml
  frontend/petkinFE/app/src/main/res/values/themes.xml
  frontend/petkinFE/gradle/libs.versions.toml
Labels: 🎨 Design, 🐳 FE

#14 [Feat] 카카오 로그인 구현
  frontend/petkinFE/app/build.gradle.kts
  frontend/petkinFE/app/src/main/AndroidManifest.xml
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/App.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/AppNavigator.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainActivity.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MyApplication.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/login/LoginScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/login/LoginViewModel.kt
  frontend/petkinFE/build.gradle.kts
  frontend/petkinFE/gradle/libs.versions.toml
  frontend/petkinFE/settings.gradle.kts
Labels: ⭐️ Feature, 🐳 FE

#22 [Feature/FE&BE] 카카오 로그인 서버 연동 테스트
  backend/todosapp.db
  frontend/petkinFE/app/build.gradle.kts
  frontend/petkinFE/app/src/main/AndroidManifest.xml
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/App.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/AppNavigator.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainActivity.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MyApplication.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/local/TokenDataSource.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/mapper/AuthMapper.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/.gitkeep
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/api/AuthApi.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/dto/AuthDto.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/AuthRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AppModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AuthInterceptor.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/NetworkModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/RepositoryModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/TokenAuthenticator.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/HealthRecord.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/Pet.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/UserProfile.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/AuthRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/HealthRecordRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/PetRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/AutoLoginUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetTodayRecordUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeView.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/login/LoginScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/login/LoginViewModel.kt
  frontend/petkinFE/app/src/main/res/xml/network_security_config.xml
  frontend/petkinFE/gradle.properties
  frontend/petkinFE/gradle/libs.versions.toml
  frontend/petkinFE/gradle/wrapper/gradle-wrapper.properties
Labels: ⭐️ Feature, 📭 API, 🐧 BE, 🐳 FE

#23 [Feature/BE] Authorize 추가
  backend/petkinApp/__pycache__/database.cpython-313.pyc
  backend/petkinApp/__pycache__/main.cpython-313.pyc
  backend/petkinApp/__pycache__/models.cpython-313.pyc
  backend/petkinApp/database.py
  backend/petkinApp/main.py
  backend/petkinApp/models.py
  backend/petkinApp/routers/__pycache__/customers.cpython-313.pyc
  backend/petkinApp/routers/__pycache__/todos.cpython-313.pyc
  backend/petkinApp/routers/customers.py
  backend/petkinApp/routers/todos.py
  backend/requirements.txt
Labels: 📭 API, 🐧 BE

#24 [Feature/BE] 카카오 로그인 마무리(db저장 확인)
  backend/petkinApp/__pycache__/models.cpython-313.pyc
  backend/petkinApp/models.py
  backend/petkinApp/routers/__pycache__/customers.cpython-313.pyc
  backend/petkinApp/routers/customers.py
  backend/petkinApp/security.py
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/AppNavigator.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/navigation/PetkinNavigation.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/navigation/PetkinScreens.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/calendar/CalendarScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
Labels: ⭐️ Feature, 🐧 BE

#25 [Feature/BE] 카카오 로그인 구현 & 앱 연동 확인
  backend/petkinApp/__pycache__/models.cpython-313.pyc
  backend/petkinApp/models.py
  backend/petkinApp/routers/__pycache__/customers.cpython-313.pyc
  backend/petkinApp/routers/customers.py
  backend/petkinApp/security.py
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/AppNavigator.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/navigation/PetkinNavigation.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/navigation/PetkinScreens.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/calendar/CalendarScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
Labels: ⭐️ Feature, 📭 API, 🐧 BE, 🐳 FE
