Repository aengzu/AILectureProject, pull requests merged in 2024-12, with the labels that each got.

#31 [Design/FE] 하단바 디자인 수정
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/calendar/CalendarScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/BottomNavigationBar.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/widgets/CardSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/components/TitleSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/model/IconUIModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/ui/theme/Theme.kt
  frontend/petkinFE/app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🐳 FE

#33 [Feature/FE] 반려동물 관련 도메인 레이어 구성
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/local/SharedPrefManager.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/mapper/PetMapper.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/dto/PetDto.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/PetRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/NetworkModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/Pet.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/PetRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/DeletePetUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetMyPetsUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/RegisterPetUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/UpdatePetUseCase.kt
Labels: 🐳 FE

#40 [Fix/BE] refresh 관련 api 추가
  backend/petkinApp/routers/__pycache__/customers.cpython-313.pyc
  backend/petkinApp/routers/customers.py
  backend/petkinApp/schemas/customers.py
Labels: 🕷️ Bug, 🐧 BE

#42 [Feature/FE] 토큰 갱신 코드 작성 & 반려동물 조회 페이지 구현
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/local/TokenDataSource.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/mapper/AuthMapper.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/mapper/PetMapper.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/api/PetApi.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/dto/AuthDto.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/dto/PetDto.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/AuthRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/PetRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AppModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AuthInterceptor.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/TokenAuthenticator.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/UserProfile.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/AuthRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetMyPetsUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetUserInfoUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/RegisterPetUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/.gitkeep
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/calendar/CalendarScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/pet/PetRegistrationScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/pet/PetRegistrationViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/user/UserScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/user/UserViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/utils/DateFormat.kt
  frontend/petkinFE/app/src/main/res/drawable/res_cat.png
  frontend/petkinFE/app/src/main/res/drawable/res_dog.png
Labels: ⭐️ Feature, 🎨 Design, 🐳 FE

#44 [Chore/BE] torch 라이브러리 추가로 인해 requirements 수정
  backend/requirements.txt
Labels: ⚙️ Setting, 🐧 BE

#45 [Chore/BE] requirements.txt 수정
  backend/petkinApp/__pycache__/__init__.cpython-311.pyc
  backend/petkinApp/__pycache__/database.cpython-311.pyc
  backend/petkinApp/__pycache__/main.cpython-311.pyc
  backend/petkinApp/__pycache__/models.cpython-311.pyc
  backend/petkinApp/main.py
  backend/petkinApp/models.py
  backend/petkinApp/routers/__pycache__/__init__.cpython-311.pyc
  backend/petkinApp/routers/__pycache__/customers.cpython-311.pyc
  backend/requirements.txt
Labels: ⚙️ Setting, 🐧 BE

#48 [Design/FE] 날라간 디자인 복구..
  backend/petkinApp/routers/prediction.py
  frontend/petkinFE/.idea/deploymentTargetDropDown.xml
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/MainActivity.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/HealthRecordRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/RepositoryModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/HealthRecord.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/HealthRecordRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetTodayRecordUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/navigation/PetkinNavigation.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/calendar/CalendarScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/login/LoginScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/ui/theme/Theme.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/utils/DateFormat.kt
Labels: 🎨 Design, 🐳 FE

#49 [Feature/BE] 건강 기록 생성 api 구현
  backend/petkinApp/__pycache__/main.cpython-311.pyc
  backend/petkinApp/__pycache__/models.cpython-311.pyc
  backend/petkinApp/main.py
  backend/petkinApp/models.py
  backend/petkinApp/routers/__pycache__/customers.cpython-311.pyc
  backend/petkinApp/routers/health_records.py
  backend/petkinApp/schemas/health_records.py
Labels: 📭 API, 🐧 BE

#51 [Feature/BE] 건강 기록 조회 api 구현
  backend/petkinApp/routers/__pycache__/todos.cpython-311.pyc
  backend/petkinApp/routers/__pycache__/todos.cpython-312.pyc
  backend/petkinApp/routers/__pycache__/todos.cpython-313.pyc
  backend/petkinApp/routers/health_records.py
  backend/petkinApp/routers/todos.py
  backend/petkinApp/schemas/health_records.py
Labels: 📭 API, 🐧 BE

#52 [Feature/Home] 반려동물 예측용 사진 업로드 구현 (서버 연동 X, 로컬 db 저장)
  frontend/petkinFE/.idea/deploymentTargetDropDown.xml
  frontend/petkinFE/app/build.gradle.kts
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/local/dao/PhotoDao.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/local/entity/PhotoEntity.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/PredictionRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AppDatabase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AppModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/RepositoryModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/HealthRecord.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/PredictionRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetTodayPredictionUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetTodayRecordUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/SavePhotoUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/calendar/CalendarScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/CardSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/IconSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeViewModel.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/utils/handleUri.kt
Labels: ⭐️ Feature, 🐳 FE

#50 [Update/AI] AI 배포 코드 임시 업로드
  backend/.gitignore
  backend/petkinApp/__pycache__/__init__.cpython-311.pyc
  backend/petkinApp/__pycache__/__init__.cpython-312.pyc
  backend/petkinApp/__pycache__/__init__.cpython-313.pyc
  backend/petkinApp/__pycache__/database.cpython-311.pyc
  backend/petkinApp/__pycache__/main.cpython-311.pyc
  backend/petkinApp/__pycache__/models.cpython-311.pyc
  backend/petkinApp/main.py
  backend/petkinApp/routers/__pycache__/__init__.cpython-311.pyc
  backend/petkinApp/routers/__pycache__/customers.cpython-311.pyc
  backend/petkinApp/routers/prediction.py
  backend/requirements.txt
Labels: 📭 API, 🤖 AI, 🐧 BE

#53 [Refactor/AI] 모델 피쳐 전처리 코드 업데이트
  backend/petkinApp/__pycache__/main.cpython-311.pyc
  backend/petkinApp/__pycache__/models.cpython-311.pyc
  backend/petkinApp/main.py
  backend/petkinApp/models.py
  backend/petkinApp/routers/pets.py
  backend/petkinApp/routers/prediction.py
  backend/requirements.txt
  backend/static/uploads/5_20241210184023.jpg
  backend/static/uploads/5_20241210184101.jpg
  backend/static/uploads/5_20241210184228.jpg
  backend/static/uploads/5_20241210184515.jpg
  backend/static/uploads/5_20241210185726.jpg
Labels: 📭 API, 🤖 AI

#56 [Feature/FE] 홈화면 진입 시 기존 예측 결과 있다면 불러와서 띄우기 구현
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/local/dao/PhotoDao.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/mapper/PredictionMapper.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/api/PredictionApi.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/dto/PredictionDto.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/PetRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/PredictionRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/di/AppModule.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/Prediction.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/PredictionRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetTodayPredictionUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/CardSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeViewModel.kt
Labels: 💉 Fix, 🐳 FE

#57 [Chore/AI] 사진 확장자 수정 및 gitignore 에 사진 포함안하도록 설정
  backend/.gitignore
  backend/petkinApp/routers/prediction.py
  backend/static/uploads/5_20241210184023.jpg
  backend/static/uploads/5_20241210184101.jpg
  backend/static/uploads/5_20241210184228.jpg
  backend/static/uploads/5_20241210184515.jpg
  backend/static/uploads/5_20241210185726.jpg
  backend/static/uploads/6_20241212052309.webp
Labels: 🤖 AI, 🐧 BE

#59 [Chore/BE] Docker 파일 작성
  backend/Dockerfile
  backend/petkinApp/routers/prediction.py
Labels: ⚙️ Setting, 🐧 BE

#60 [Chore/BE] Deploy 세팅
  backend/.gitignore
  backend/Dockerfile
  backend/Dump20241216/petkin_db_AIResult.sql
  backend/Dump20241216/petkin_db_Customers.sql
  backend/Dump20241216/petkin_db_DiseasePredictionRecord.sql
  backend/Dump20241216/petkin_db_DiseaseType.sql
  backend/Dump20241216/petkin_db_HealthRecord.sql
  backend/Dump20241216/petkin_db_ItemType.sql
  backend/Dump20241216/petkin_db_Pet.sql
  backend/Dump20241216/petkin_db_pets.sql
  backend/docker-compose.yml
  backend/petkinApp/__pycache__/main.cpython-311.pyc
  backend/petkinApp/__pycache__/models.cpython-311.pyc
  backend/petkinApp/main.py
  backend/requirements.txt
Labels: 🌎 Deploy, 🐧 BE

#61 [Chore/FE] backend 연결 설정
  frontend/petkinFE/app/src/main/res/xml/network_security_config.xml
Labels: 🌎 Deploy, 🐳 FE

#63 [Feature/FE] 서버에서 오늘 기록 조회 연동 (홈화면)
  backend/backend.tar
  backend/petkinApp/__pycache__/main.cpython-311.pyc
  backend/petkinApp/routers/health_records.py
  backend/petkinApp/routers/prediction.py
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/mapper/HealthRecordMapper.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/api/HealthRecordApi.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/remote/dto/HealthRecordDto.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/data/repository/HealthRecordRepositoryImpl.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/model/HealthRecord.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/repository/HealthRecordRepository.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/domain/usecases/GetTodayRecordUseCase.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/core/CardSection.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeScreen.kt
  frontend/petkinFE/app/src/main/java/com/rtl/petkinfe/presentation/view/home/HomeViewModel.kt
Labels: ⭐️ Feature, 🐳 FE
